Sync repo with Google3
GoogleCloudPlatform/appengine-php-sdk pull request #27
Opened 2021-04-07 17:27 UTC by zachluna

Sync Git to the newer changes which exist in Google3.

2021-04-15 01:19 UTC, bshaffer requested changes
All these changes look good except for the missing changes in https://github.com/GoogleCloudPlatform/appengine-php-sdk/commit/1377c619e2415fc9fca3a1e85cebb6d8a4dd3d98

I recommend we make the changes from https://github.com/GoogleCloudPlatform/appengine-php-sdk/commit/1377c619e2415fc9fca3a1e85cebb6d8a4dd3d98 internally, and then sync to here again. The result should be 👍

2021-04-15 01:19 UTC, bshaffer commented on google/appengine/api/mail/BaseMessage.php
> +      $error = sprintf("Input header '%s: %s' is not whitelisted for use with" .
I think we should merge the changes from https://github.com/GoogleCloudPlatform/appengine-php-sdk/commit/1377c619e2415fc9fca3a1e85cebb6d8a4dd3d98 into Google3, rather than revert the changes here.

2021-04-15 01:19 UTC, bshaffer commented on google/appengine/api/mail/MessageTest.php
> +  public function testAddHeaderNonWhitelisted() {
Same here, this was done in https://github.com/GoogleCloudPlatform/appengine-php-sdk/commit/1377c619e2415fc9fca3a1e85cebb6d8a4dd3d98 and we should make those changes internally and resync so they are not overwritten.

2021-04-15 20:23 UTC, zachluna commented on google/appengine/api/mail/BaseMessage.php
> +      $error = sprintf("Input header '%s: %s' is not whitelisted for use with" .
Sounds good, I merged changes into g3 and removing from here, thanks.

2021-04-15 20:24 UTC, zachluna commented on google/appengine/api/mail/MessageTest.php
> +  public function testAddHeaderNonWhitelisted() {
Sounds good, I merged changes into g3 and removing from here, thanks.

2021-04-16 15:21 UTC, bshaffer approved these changes

2021-04-16 16:36 UTC, merged