Integrate MemcacheSessionHandler Api
GoogleCloudPlatform/appengine-php-sdk pull request #69
Opened 2021-05-26 16:49 UTC by zachluna

2021-06-02 01:42 UTC, jinglundong commented on src/Api/Memcache/MemcacheOptIn.php
> +	define('MEMCACHE_HAVE_SESSION', 1); // See ext/session/MemcacheSessionHandler.
I don't see a reference to MEMCACHE_HAVE_SESSION in ext/session/MemcacheSessionHandler. Can you share more history/context?

2021-06-02 01:47 UTC, jinglundong commented on src/Ext/Session/MemcacheContainer.php
> +   * Initialises a Memcache instance
nit and not super actionable: have you considered google's phpdoc format? 

Comments: phpdoc (similar to javadoc), and follow the C++ style in spirit. See http://www.phpdoc.org for detailed information.

2021-06-02 01:50 UTC, jinglundong commented on src/Ext/Session/MemcacheSessionHandler.php
>     * @return string data associated with that ID or bool false on failure
The new implementation could return empty string. Is this doc still accurate?

2021-06-02 01:53 UTC, jinglundong commented on tests/Ext/Session/MemcacheSessionHandlerTest.php
> -  public function setUp(): void {
Any specific reasons to remove this setUp method? It's quite clear that such skip call is no longer needed. What about `parent::setUp();`?

2021-06-02 01:55 UTC, jinglundong requested changes
Looks good overall. I had a few minor comments.

2021-06-02 16:49 UTC, zachluna commented on tests/Ext/Session/MemcacheSessionHandlerTest.php
> -  public function setUp(): void {
Setup is no longer needed since using `@runTestsInSeparateProcesses`

2021-06-02 16:56 UTC, zachluna commented on src/Ext/Session/MemcacheContainer.php
> +   * Initialises a Memcache instance
I see, I'll take a look at this. This file is unmodified, moved from  MemcacheSessionHandler.php to MemcacheContainer.php since we have to follow the rule of 1 class per document.

2021-06-02 16:59 UTC, zachluna commented on src/Api/Memcache/MemcacheOptIn.php
> +	define('MEMCACHE_HAVE_SESSION', 1); // See ext/session/MemcacheSessionHandler.
This was moved from Memcache.php to the Memcache Opt In file. It's basically parts of the Memcache that's not active unless users want to opt in to old behavior. This is a global constant MEMCACHE_HAVE_SESSION which was the last test in MemcacheSessionHandlerTest.php which was removed since it is no longer global unless the user opts in.

2021-06-02 17:08 UTC, zachluna commented on src/Api/Memcache/MemcacheOptIn.php
> +	define('MEMCACHE_HAVE_SESSION', 1); // See ext/session/MemcacheSessionHandler.
Another thing to consider is that only classes are loaded by the composer autoloader, making it impossible to access all functions and constants declared outside of a class from outside the namespace. i.e. calling `use Google\AppEngine\Api\Memcache\MEMCACHE_HAVE_SESSION` does not work and it is impossible to access `MEMCACHE_HAVE_SESSION` from inside Memcache.php since the autoloader makes no path to it. Therefore, it must be added to the autoloader in a special way, from MemcacheOptIn.php.

2021-06-02 17:45 UTC, zachluna commented on src/Ext/Session/MemcacheSessionHandler.php
>     * @return string data associated with that ID or bool false on failure
Thanks for pointing this out! updated.

2021-06-04 03:21 UTC, jinglundong approved these changes

2021-06-07 23:01 UTC, merged